version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Set environment"
          command: |
            sudo apt-get update
            sudo apt install python3.8-venv
            sudo apt-get install python3-pip
            python3 -m venv env/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: "Run tests"
          command: |
            python3 unittests.py

workflows:
  build-workflow:
    jobs:
      - build
